version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    volumes:
      - ./frontend:/frontend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"  # Expose backend on port 5000
    volumes:
      - ./backend:/backend
